---
title: "r2d3 Flex Dashboard"
author: "Zack Larsen"
date: "June 9, 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(r2d3)
bars <- c(10, 20, 30)


bar_data <- data.frame(stringsAsFactors=FALSE,
        name = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L",
                 "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X",
                 "Y", "Z"),
       value = c(0.08167, 0.01492, 0.02782, 0.04253, 0.12702, 0.02288, 0.02015,
                 0.06094, 0.06966, 0.00153, 0.00772, 0.04025, 0.02406, 0.06749,
                 0.07507, 0.01929, 0.00095, 0.05987, 0.06327, 0.09056, 0.02758,
                 0.00978, 0.0236, 0.0015, 0.01974, 0.00074)
)



```

Landing Page
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Bubble Chart

```{r bubbles, cache=TRUE}

r2d3::r2d3(data = read.csv("https://raw.githubusercontent.com/rstudio/r2d3/master/vignettes/gallery/bubbles/flare.csv"), d3_version = 4, script = "bubbles.js")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Stacked Histogram

```{r stacked_histo}

r2d3::r2d3(d3_version = 4, script = "stackedbars.js")

```

### Calendar

```{r calendar}

r2d3::r2d3(data = read.csv("https://raw.githubusercontent.com/rstudio/r2d3/master/vignettes/gallery/calendar/dji-latest.csv"), d3_version = 4, container = "div", options = list(start = 2006, end = 2011), script = "calendar.js")

```




Page 2
=======================================================================

Column {data-width=550}
-----------------------------------------------------------------------

### Voronoi

```{r Voronoi, cache=TRUE}

r2d3::r2d3(d3_version = 4, script = "voronoi.js")

```

Column {data-width=450}
-----------------------------------------------------------------------

### Treemap

```{r Treemap}

r2d3::r2d3(data = jsonlite::read_json("https://raw.githubusercontent.com/rstudio/r2d3/master/vignettes/gallery/treemap/flare.json"), d3_version = 4, script = "treemap.js")

```

### Steamgraph

```{r steamgraph}

r2d3::r2d3(data=c(), d3_version = 4, script = "streamgraph.js")

```


Page 3
=======================================================================


Column {data-width=550}
-----------------------------------------------------------------------

### D3 cell

```{d3 data=c(), d3_version = 4}
var n = 20, // number of layers
    m = 200, // number of samples per layer
    k = 10; // number of bumps per layer

var stack = d3.stack().keys(d3.range(n)).offset(d3.stackOffsetWiggle),
    layers0 = stack(d3.transpose(d3.range(n).map(function() { return bumps(m, k); }))),
    layers1 = stack(d3.transpose(d3.range(n).map(function() { return bumps(m, k); }))),
    layers = layers0.concat(layers1);

var x = d3.scaleLinear()
    .domain([0, m - 1])
    .range([0, width]);

var y = d3.scaleLinear()
    .domain([d3.min(layers, stackMin), d3.max(layers, stackMax)])
    .range([height, 0]);

var z = d3.interpolateCool;

var area = d3.area()
    .x(function(d, i) { return x(i); })
    .y0(function(d) { return y(d[0]); })
    .y1(function(d) { return y(d[1]); });

var widthOrginal = width;
var heightOrginal = height;
var root = svg.append("g");

root
  .selectAll("path")
  .data(layers0)
  .enter().append("path")
    .attr("d", area)
    .attr("fill", function() { return z(Math.random()); });

function stackMax(layer) {
  return d3.max(layer, function(d) { return d[1]; });
}

function stackMin(layer) {
  return d3.min(layer, function(d) { return d[0]; });
}

function transition() {
  var t;
  d3.selectAll("path")
    .data((t = layers1, layers1 = layers0, layers0 = t))
    .transition()
      .duration(2500)
      .attr("d", area);
}

// Inspired by Lee Byron’s test data generator.
function bumps(n, m) {
  var a = [], i;
  for (i = 0; i < n; ++i) a[i] = 0;
  for (i = 0; i < m; ++i) bump(a, n);
  return a;
}

function bump(a, n) {
  var x = 1 / (0.1 + Math.random()),
      y = 2 * Math.random() - 0.5,
      z = 10 / (0.1 + Math.random());
  for (var i = 0; i < n; i++) {
    var w = (i / n - y) * z;
    a[i] += x * Math.exp(-w * w);
  }
}

r2d3.onResize(function(width, height) {
  root.attr("transform", "scale(" + width / widthOrginal + "," + height / heightOrginal + ")");
});

```


Column {data-width=450}
-----------------------------------------------------------------------

### From r2d3 site

```{d3 data=bars, options=list(color = 'orange')}

svg.selectAll('rect')
  .data(data)
  .enter()
    .append('rect')
      .attr('width', function(d) { return d * 10; })
      .attr('height', '20px')
      .attr('y', function(d, i) { return i * 22; })
      .attr('fill', options.color);

```


### Bostock bar

```{d3 data = bar_data}

var width = 960,
    height = 500;

var y = d3.scale.linear()
    .range([height, 0]);

var chart = d3.select(".chart")
    .attr("width", width)
    .attr("height", height);

d3.tsv(bar_data, type, function(error, data) {
  y.domain([0, d3.max(data, function(d) { return d.value; })]);

  var barWidth = width / data.length;

  var bar = chart.selectAll("g")
      .data(data)
    .enter().append("g")
      .attr("transform", function(d, i) { return "translate(" + i * barWidth + ",0)"; });

  bar.append("rect")
      .attr("y", function(d) { return y(d.value); })
      .attr("height", function(d) { return height - y(d.value); })
      .attr("width", barWidth - 1);

  bar.append("text")
      .attr("x", barWidth / 2)
      .attr("y", function(d) { return y(d.value) + 3; })
      .attr("dy", ".75em")
      .text(function(d) { return d.value; });
});

function type(d) {
  d.value = +d.value; // coerce to number
  return d;
}

```